<?php 
/**
 * Partial that contains html for framework version block
 * 
 * @category  scripts
 * @package   NotesNotes
 * @copyright Copyright (C) 2009 - Present, Alexander A. Steshenko
 * @author    Alexander A. Steshenko <lcfsoft@gmail.com> {@link http://lcf.name} 
 * @license   New BSD {@link http://www.opensource.org/licenses/bsd-license.php}
 */
?>
<div id="framework-version">
    Zend Framework <?php echo $this->version; ?>
</div>
