<?php 
/**
 * Initial note text content
 * 
 * @category  scripts
 * @package   NotesNotes
 * @copyright Copyright (C) 2009 - Present, Alexander A. Steshenko
 * @author    Alexander A. Steshenko <lcfsoft@gmail.com> {@link http://lcf.name} 
 * @license   New BSD {@link http://www.opensource.org/licenses/bsd-license.php}
 */
?>
This is a Note.

You can move it all around the page, resize it, edit its content.

Also you can add your own notes by clicking "Add note" buttons in the top left corner of the page and
place them where ever you want.

You can use the page with your notes by yourself or give the page's link to your friends or colleagues and work with the notes together.

Each page has its own address. Here is yours:
 
http://notes-notes.com/<?php echo $this->page; ?>


You can create more new pages by clicking "New page" button in the right top corner of the page, or delete it by clicking "Delete page".

To remember all pages just add them to your browser's favorites list.
