<?php 
/**
 * Error html page. I used when html context is active.
 * 
 * @category  scripts
 * @package   NotesNotes
 * @copyright Copyright (C) 2009 - Present, Alexander A. Steshenko
 * @author    Alexander A. Steshenko <lcfsoft@gmail.com> {@link http://lcf.name} 
 * @license   New BSD {@link http://www.opensource.org/licenses/bsd-license.php}
 */
?>
<div>
<?php $this->headTitle('Error occured :('); ?>
Error occured: <?php echo $this->error ?><br/>
Please try again later or try to go to the <a href="/">index page</a>
</div>